name=SeedVerses
version=1.0.0
author=Leonardo Rakotondramanana
maintainer=Leonardo Rakotondramanana <leonardorak98@gmail.com>
sentence=A lightweight client to fetch multilingual micro Bible verses from GitHub.
paragraph=This library connects seamlessly to the seed-verses open-source dataset via HTTPS. It allows ESP32 and ESP8266 microcontrollers to fetch, filter by tags, and display short Bible verses. Ideal for IoT projects, ticket dispensers, and smart displays.
category=Communication
url=https://github.com/leorak98/seed-verses
architectures=esp32,esp8266
depends=ArduinoJson